name: Run Python Script Hourly and Save Results

on:
  schedule:
    - cron: '0 * * * *'  # This runs at the start of every hour
  workflow_dispatch:  # This allows manual triggers

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Create data directory if it doesn't exist
    - name: Create data directory
      run: mkdir -p data

    - name: Run script
      run: python LibrarySeats.py

    - name: Commit and push if it changed
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # Use the secret here
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        if [ -f data/results.csv ]; then
        git add data/results.csv
        git commit -m "Update results [skip ci]" || exit 0
        git push https://$GITHUB_TOKEN@github.com/Adupadu123/LibrarySeats.git HEAD:main
        else
          echo "No results.csv file found, skipping commit."
        fi
