name: Auto

on:
  schedule:
    - cron: '0 * * * *'  
  workflow_dispatch:  

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create data directory
      run: mkdir -p data

    - name: Run script
      run: python LibrarySeats.py

    - name: Commit and push if it changed
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Update CSV [skip ci]" || exit 0
        git push origin ophr
